CC=g++
CFLAGS=-c -Wall -std=c++11 -g
LDFLAGS=
SOURCES=globals.cpp actin.cpp actin_ensemble.cpp Link.cpp actin_ensemble_test.cpp
OBJECTS=$(SOURCES:.cpp=.o)
EXECUTABLE=ae_test

all: $(SOURCES) $(EXECUTABLE)
	
$(EXECUTABLE): $(OBJECTS)
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@

.cpp.o:
	$(CC) $(CFLAGS) $< -o $@


